name: 1. Auto-Deploy to Test
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: 'read'
  id-token: 'write'
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: '${{ vars.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ vars.SERVICE_ACCOUNT_EMAIL }}'
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: terraform init -backend-config="bucket=${{ vars.GCP_TF_STATE_BUCKET }}"
      working-directory: infrastructure/terraform/environments/test
    - name: Force Unlock GCS State
      run: gsutil rm gs://${{ vars.GCP_TF_STATE_BUCKET }}/terraform/state/test/default.tflock || true
    - name: Terraform Apply
      run: terraform apply -auto-approve -lock=false -var="project_id=${{ vars.GCP_PROJECT_ID }}" -var="environment=test"
      working-directory: infrastructure/terraform/environments/test
    - name: Configure Docker Auth
      run: gcloud auth configure-docker me-west1-docker.pkg.dev --quiet
    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME="me-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/test-banking-mesh-repo/orchestrator:${{ github.sha }}"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
    - name: Configure GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: test-banking-mesh-gke
        location: me-west1
        project_id: ${{ vars.GCP_PROJECT_ID }}
    - name: Deploy to Kubernetes
      run: |
        IMAGE_NAME="me-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/test-banking-mesh-repo/orchestrator:${{ github.sha }}"
        STATIC_IP=$(terraform -chdir=infrastructure/terraform/environments/test output -raw orchestrator_external_ip)
        echo "STATIC_IP=$STATIC_IP" >> $GITHUB_ENV
        sed -i "s|IMAGE_PLACEHOLDER|$IMAGE_NAME|g" infrastructure/k8s/orchestrator.yaml
        sed -i "s|ENV_PLACEHOLDER|test|g" infrastructure/k8s/orchestrator.yaml
        sed -i "s|STATIC_IP_PLACEHOLDER|$STATIC_IP|g" infrastructure/k8s/orchestrator.yaml
        sed -i "s|MIN_REPLICAS_PLACEHOLDER|1|g" infrastructure/k8s/orchestrator.yaml
        sed -i "s|MAX_REPLICAS_PLACEHOLDER|2|g" infrastructure/k8s/orchestrator.yaml
        kubectl apply -f infrastructure/k8s/orchestrator.yaml
    - name: Extract External IP
      run: |
        echo "🚀 Orchestrator is LIVE at: http://${{ env.STATIC_IP }}" >> $GITHUB_STEP_SUMMARY
        echo "Stress Test Endpoint: http://${{ env.STATIC_IP }}/stress_test" >> $GITHUB_STEP_SUMMARY
